// Generates docs/ARCHITECTURE.md — a module-level Mermaid map of the real
// dependency graph, from the SAME source Sheriff enforces the boundaries with
// (`getProjectData`): the diagram and the rules cannot disagree, and a feature
// that emerges (ADR-0006) appears on the map the moment it is extracted.
//
// Run: pnpm arch:map   (the gate's docs/architecture.spec.ts fails on drift)
//
// The map shows the graph REACHABLE from the Sheriff entry points — exactly
// what `check:arch` verifies. An empty nursery or a not-yet-wired file does
// not appear: the map draws the shipped architecture, not the aspiration.

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { getProjectData } from '@softarc/sheriff-core'
import { config } from '../sheriff.config.ts'

export const ARCH_BEGIN =
  '<!-- arch:begin — generated by `pnpm arch:map`, do not edit -->'
export const ARCH_END = '<!-- arch:end -->'

/** The slice of Sheriff's ProjectData this generator reads. */
interface FileEntry {
  readonly module: string
  readonly tags: readonly string[]
  readonly imports: readonly string[]
}

const posix = (path: string): string => path.replaceAll('\\', '/')
const idOf = (module: string): string => module.replace(/[^A-Za-z0-9]/g, '_')

interface ModuleNode {
  readonly module: string
  readonly tags: readonly string[]
  readonly pkg: string | null
  readonly feature: string | null
  readonly label: string
}

function nodeOf(module: string, tags: readonly string[]): ModuleNode {
  const pkg = module.match(/^packages\/[^/]+/)?.[0] ?? null
  const feature =
    tags.find((t) => t.startsWith('feature:'))?.slice('feature:'.length) ?? null
  const rel = pkg
    ? module.slice(`${pkg}/src`.length).replace(/^\//, '')
    : module
  const label = rel === '' ? tags.join(', ') : rel
  return { module, tags, pkg, feature, label }
}

/** Fold file-level graphs (one per entry point) into one module-level map. */
export function mermaidOf(datas: readonly Record<string, FileEntry>[]): string {
  const moduleOfFile = new Map<string, string>()
  const tagsOfModule = new Map<string, readonly string[]>()
  for (const data of datas) {
    for (const [file, entry] of Object.entries(data)) {
      moduleOfFile.set(posix(file), posix(entry.module))
      tagsOfModule.set(posix(entry.module), entry.tags)
    }
  }

  const edges = new Set<string>()
  for (const data of datas) {
    for (const [file, entry] of Object.entries(data)) {
      const from = moduleOfFile.get(posix(file))
      for (const imported of entry.imports) {
        const to = moduleOfFile.get(posix(imported))
        if (from !== undefined && to !== undefined && from !== to) {
          edges.add(`${idOf(from)} --> ${idOf(to)}`)
        }
      }
    }
  }

  const nodes = [...tagsOfModule.entries()]
    .map(([module, tags]) => nodeOf(module, tags))
    .sort((a, b) => a.module.localeCompare(b.module))

  const lines: string[] = ['flowchart LR']
  const packages = [
    ...new Set(nodes.map((n) => n.pkg).filter((p): p is string => p !== null))
  ].sort()

  for (const node of nodes.filter((n) => n.pkg === null)) {
    lines.push(`  ${idOf(node.module)}["${node.label}"]`)
  }
  for (const pkg of packages) {
    lines.push(`  subgraph pkg_${idOf(pkg)}["${pkg}"]`)
    const inPkg = nodes.filter((n) => n.pkg === pkg)
    for (const node of inPkg.filter((n) => n.feature === null)) {
      lines.push(`    ${idOf(node.module)}["${node.label}"]`)
    }
    const features = [
      ...new Set(
        inPkg.map((n) => n.feature).filter((f): f is string => f !== null)
      )
    ].sort()
    for (const feature of features) {
      lines.push(`    subgraph feature_${idOf(feature)}["feature: ${feature}"]`)
      for (const node of inPkg.filter((n) => n.feature === feature)) {
        lines.push(`      ${idOf(node.module)}["${node.label}"]`)
      }
      lines.push('    end')
    }
    lines.push('  end')
  }
  for (const edge of [...edges].sort()) {
    lines.push(`  ${edge}`)
  }
  return lines.join('\n')
}

/** Rewrite docs/ARCHITECTURE.md from the current tree. */
export function writeArchitectureMap(root: string): void {
  const mermaid = mermaidOf(
    Object.values(config.entryPoints ?? {}).map((entry) =>
      getProjectData(entry, root)
    )
  )
  const doc = [
    '# Architecture map',
    '',
    '> **Generated** by `pnpm arch:map` — do not edit by hand. The gate',
    '> (`docs/architecture.spec.ts`) fails when this file drifts from the tree:',
    '> regenerate it in the same commit as the change that reshaped the graph.',
    '',
    'Nodes are the modules **Sheriff** verifies (`pnpm check:arch` and this map',
    'read the same graph, so they cannot disagree); arrows are real imports,',
    'folded to module level. A feature extracted from the nursery',
    '([ADR-0006](adr/0006-emergent-feature-modules.md)) appears as a subgraph',
    'the moment it exists. The map shows the graph **reachable from the entry',
    'points** — an empty nursery or an unwired file does not appear: this is',
    'the shipped architecture, not the aspiration.',
    '',
    ARCH_BEGIN,
    '',
    '```mermaid',
    mermaid,
    '```',
    '',
    ARCH_END,
    ''
  ].join('\n')
  writeFileSync(resolve(root, 'docs/ARCHITECTURE.md'), doc)
}

const executedDirectly =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
if (executedDirectly) {
  const root = fileURLToPath(new URL('..', import.meta.url))
  writeArchitectureMap(root)
  console.log('docs/ARCHITECTURE.md regenerated from the current tree.')
}
