// Generates docs/ARCHITECTURE.md — a module-level Mermaid map of the real
// dependency graph, from the SAME source Sheriff enforces the boundaries with
// (`getProjectData`): the diagram and the rules cannot disagree, and a feature
// that emerges (ADR-0006) appears on the map the moment it is extracted.
//
// Run: pnpm arch:map   (the gate's docs/architecture.spec.ts fails on drift)
//
// The map shows the graph REACHABLE from the Sheriff entry points — exactly
// what `check:arch` verifies. An empty nursery or a not-yet-wired file does
// not appear: the map draws the shipped architecture, not the aspiration.

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { getProjectData } from '@softarc/sheriff-core'
import { config } from '../sheriff.config.ts'

export const ARCH_BEGIN =
  '<!-- arch:begin — generated by `pnpm arch:map`, do not edit -->'
export const ARCH_END = '<!-- arch:end -->'

/** The slice of Sheriff's ProjectData this generator reads. */
interface FileEntry {
  readonly module: string
  readonly tags: readonly string[]
  readonly imports: readonly string[]
}

const posix = (path: string): string => path.replaceAll('\\', '/')
const idOf = (module: string): string => module.replace(/[^A-Za-z0-9]/g, '_')

interface ModuleNode {
  readonly module: string
  readonly tags: readonly string[]
  readonly pkg: string | null
  readonly feature: string | null
  readonly label: string
}

function nodeOf(module: string, tags: readonly string[]): ModuleNode {
  const pkg = module.match(/^packages\/[^/]+/)?.[0] ?? null
  const feature =
    tags.find((t) => t.startsWith('feature:'))?.slice('feature:'.length) ?? null
  const rel = pkg
    ? module.slice(`${pkg}/src`.length).replace(/^\//, '')
    : module
  const label = rel === '' ? tags.join(', ') : rel
  return { module, tags, pkg, feature, label }
}

// Code-unit order on purpose, NOT localeCompare: the map is a golden file
// compared across OSes, and locale-aware order varies with the ICU build.
const byCodeUnit = (a: string, b: string): number => {
  if (a < b) {
    return -1
  }
  return a > b ? 1 : 0
}

const uniqueSorted = (values: readonly (string | null)[]): string[] =>
  [...new Set(values.filter((v): v is string => v !== null))].sort(byCodeUnit)

const nodeLine = (node: ModuleNode, indent: string): string =>
  `${indent}${idOf(node.module)}["${node.label}"]`

/** File-level graphs folded to module level: one node set, deduped edges. */
function foldedGraphOf(datas: readonly Record<string, FileEntry>[]): {
  nodes: readonly ModuleNode[]
  edges: readonly string[]
} {
  const moduleOfFile = new Map<string, string>()
  const tagsOfModule = new Map<string, readonly string[]>()
  const files = datas.flatMap((data) => Object.entries(data))
  for (const [file, entry] of files) {
    moduleOfFile.set(posix(file), posix(entry.module))
    tagsOfModule.set(posix(entry.module), entry.tags)
  }

  const edges = new Set<string>()
  for (const [file, entry] of files) {
    const from = moduleOfFile.get(posix(file))
    for (const imported of entry.imports) {
      const to = moduleOfFile.get(posix(imported))
      if (from !== undefined && to !== undefined && from !== to) {
        edges.add(`${idOf(from)} --> ${idOf(to)}`)
      }
    }
  }

  const nodes = [...tagsOfModule.entries()]
    .map(([module, tags]) => nodeOf(module, tags))
    .sort((a, b) => byCodeUnit(a.module, b.module))
  return { nodes, edges: [...edges].sort(byCodeUnit) }
}

const featureLines = (
  feature: string,
  members: readonly ModuleNode[]
): string[] => [
  `    subgraph feature_${idOf(feature)}["feature: ${feature}"]`,
  ...members.map((node) => nodeLine(node, '      ')),
  '    end'
]

const packageLines = (
  pkg: string,
  members: readonly ModuleNode[]
): string[] => [
  `  subgraph pkg_${idOf(pkg)}["${pkg}"]`,
  ...members.filter((n) => n.feature === null).map((n) => nodeLine(n, '    ')),
  ...uniqueSorted(members.map((n) => n.feature)).flatMap((feature) =>
    featureLines(
      feature,
      members.filter((n) => n.feature === feature)
    )
  ),
  '  end'
]

/** Fold file-level graphs (one per entry point) into one module-level map. */
export function mermaidOf(datas: readonly Record<string, FileEntry>[]): string {
  const { nodes, edges } = foldedGraphOf(datas)
  return [
    'flowchart LR',
    ...nodes.filter((n) => n.pkg === null).map((n) => nodeLine(n, '  ')),
    ...uniqueSorted(nodes.map((n) => n.pkg)).flatMap((pkg) =>
      packageLines(
        pkg,
        nodes.filter((n) => n.pkg === pkg)
      )
    ),
    ...edges.map((edge) => `  ${edge}`)
  ].join('\n')
}

/**
 * Acquire the graph and fold it — the whole protocol `pnpm arch:map` runs.
 *
 * This is the module's seam, and it exists because there are exactly TWO
 * callers who need the current map and only one of them may write a file: the
 * generator below, and the gate (`docs/architecture.spec.ts`). Before this was
 * exported, the checker restated the fold verbatim and imported `config` and
 * `getProjectData` purely to reconstruct it — so it verified its own copy of
 * the protocol and never the path `pnpm arch:map` takes.
 */
export function currentMermaid(root: string): string {
  return mermaidOf(
    Object.values(config.entryPoints ?? {}).map((entry) =>
      getProjectData(entry, root)
    )
  )
}

/** The generated document around a folded map — prose included. */
export function docOf(mermaid: string): string {
  return [
    '# Architecture map',
    '',
    '> **Generated** by `pnpm arch:map` — do not edit by hand. The gate',
    '> (`docs/architecture.spec.ts`) fails when this file drifts from the tree:',
    '> regenerate it in the same commit as the change that reshaped the graph.',
    '',
    'Nodes are the modules **Sheriff** verifies (`pnpm check:arch` and this map',
    'read the same graph, so they cannot disagree); arrows are real imports,',
    'folded to module level. A feature extracted from the nursery',
    '([ADR-0006](adr/0006-emergent-feature-modules.md)) appears as a subgraph',
    'the moment it exists. The map shows the graph **reachable from the entry',
    'points** — an empty nursery or an unwired file does not appear: this is',
    'the shipped architecture, not the aspiration.',
    '',
    ARCH_BEGIN,
    '',
    '```mermaid',
    mermaid,
    '```',
    '',
    ARCH_END,
    ''
  ].join('\n')
}

/** Rewrite docs/ARCHITECTURE.md from the current tree. */
export function writeArchitectureMap(root: string): void {
  writeFileSync(
    resolve(root, 'docs/ARCHITECTURE.md'),
    docOf(currentMermaid(root))
  )
}

const executedDirectly =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
if (executedDirectly) {
  const root = fileURLToPath(new URL('..', import.meta.url))
  writeArchitectureMap(root)
  console.log('docs/ARCHITECTURE.md regenerated from the current tree.')
}
